language: python
sudo: false
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- 3.8
env:
- DIST="--installpkg ./dist/ami2py-*.whl"
install:
- pip install -r requirements.txt
- pip list
- python setup.py bdist_wheel
- pip install .
script:
- pytest tests
deploy:
  provider: pypi
  user: __token__
  password:
    secure: eDNxG0TQNei7vgvd6/oG0sZxGYNl3+sr+cb9Onzu3g0wB684VDOMztjPd+2QtcHqkHNBp84BNilMsvZ3k9Wh1oR4hCtA4AWtOeB4iTLh5b9oRzs38BBUYC3eh8vUNLu72SBErabmqOtvxAG9rXAjAPAMIpX7ksODCcn5isBk4XYuh1pppHt6eeMXycgvjz0W9vemy63n3ILh1ldI8uBYYrTNLx/fozB+7Uc5rkOl3MV2iDzew0W2wjNHRJlSFCR9ZDFdembTfiN9S+kY53lo1IFEymdN7Swx0ZxEnwEDETOTnm8E56tJwNGu0au4kyeTMZhmS5ztFbkX1t3esxCVQ6uhzw/1eOwNYQyNTpmqPrWR69XUoG49hsSNGGBH4K4ZT9rUGMrPvRvaE2L+CEKiCTBz0npFVikoYNglUR9yXVUfW0d++nXn0S4CW+2zZPiRJeGtFCLzNCmYC0TpQDUaBerhTzrei9pt8d31s/fC5xWhaKtl6TaehrDBHrZbUJGAJ7gPjdLKdZRXYVk9vii2Bu3PXdEqcznnvqBddxyhb8/M9IrAE6N2ILcceNbfP/g6z34uykFx8BCc0Hv6pGjE5CSpi5ZoSQS2srbwGTGcf2yZwqQfzWsfLlKw+/5FLr0hXOomS+NN5+YscGVU4PR/biIxRLe/vxPSMuZb6uphhO4=
