[package]
name = "rust_ami_py"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_ami_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
ami2rs = { path = "../ami2rs" }
